package repoctx

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func writeRepoFile(t *testing.T,root,rel,src string){t.Helper();p:=filepath.Join(root,filepath.FromSlash(rel));if err:=os.MkdirAll(filepath.Dir(p),0o755);err!=nil{t.Fatal(err)};if err:=os.WriteFile(p,[]byte(src),0o644);err!=nil{t.Fatal(err)}}
func TestIndexGraphConfirmsJavaBusinessChainAndRejectsPackageSimilarity(t *testing.T){root:=t.TempDir();writeRepoFile(t,root,"src/OrderController.java",`package com.acme.order; import org.springframework.web.bind.annotation.RestController;
@RestController public class OrderController { private final OrderService service; public OrderController(OrderService service){this.service=service;} public Order createOrder(OrderRequest r){return service.createOrder(r);} }`);writeRepoFile(t,root,"src/OrderService.java",`package com.acme.order; import org.springframework.stereotype.Service;
@Service public class OrderService { private final OrderRepository repository; public OrderService(OrderRepository repository){this.repository=repository;} public Order createOrder(OrderRequest r){return repository.save(new Order());} }`);writeRepoFile(t,root,"src/OrderRepository.java",`package com.acme.order; import org.springframework.stereotype.Repository;
@Repository public interface OrderRepository { Order save(Order order); }`);writeRepoFile(t,root,"src/OtherController.java",`package com.acme.order; public class OtherController { public void delete(String id){} }`);idx,err:=NewIndexer(root).Build(context.Background());if err!=nil{t.Fatal(err)};chain:=confirmedChain(idx,"OrderController","createOrder","OrderService","createOrder","OrderRepository","save");if chain!="OrderController#createOrder -> OrderService#createOrder -> OrderRepository#save"{t.Fatalf("chain=%q relations=%+v unresolved=%v",chain,idx.Relations,idx.Unresolved)};ranked:=Rank(idx,Query{Text:"OrderController#createOrder"});if len(ranked)<3{t.Fatalf("ranked=%+v",ranked)};top:=[]string{ranked[0].Path,ranked[1].Path,ranked[2].Path};joined:=strings.Join(top," ");for _,want:=range []string{"OrderController.java","OrderService.java","OrderRepository.java"}{if !strings.Contains(joined,want){t.Fatalf("top=%v missing %s",top,want)}};if strings.Contains(joined,"OtherController.java"){t.Fatalf("package-similar sibling promoted: %v",top)}}
func TestIndexAmbiguousMethodTargetRemainsUnresolved(t *testing.T){root:=t.TempDir();writeRepoFile(t,root,"A.java",`class A { private final B b; A(B b){this.b=b;} void run(){b.work("x");} }`);writeRepoFile(t,root,"B.java",`class B { void work(String s){} void work(long n){} }`);idx,err:=NewIndexer(root).Build(context.Background());if err!=nil{t.Fatal(err)};for _,r:=range idx.Relations{if strings.Contains(r.To,"#work("){t.Fatalf("ambiguous call promoted: %+v",r)}};if !strings.Contains(strings.Join(idx.Unresolved,"\n"),"ambiguous"){t.Fatalf("unresolved=%v",idx.Unresolved)}}
func TestRankPriorityAndDeterminism(t *testing.T){idx:=RepositoryIndex{Files:[]SourceFile{{Path:"exact.go",Terms:[]string{"widget"}},{Path:"changed.go",Terms:[]string{"widget"}},{Path:"lexical.go",Terms:[]string{"widget"}}},Symbols:[]Symbol{{ID:"s1",Name:"Widget",Path:"exact.go",Kind:SymbolType},{ID:"s2",Name:"Other",Path:"changed.go",Kind:SymbolType},{ID:"s3",Name:"WidgetHelper",Path:"lexical.go",Kind:SymbolFunction}}};q:=Query{Text:"Widget",ChangedFiles:[]string{"changed.go"}};a:=Rank(idx,q);b:=Rank(idx,q);if !reflect.DeepEqual(a,b){t.Fatalf("rank unstable: %+v vs %+v",a,b)};if len(a)<3||a[0].Path!="exact.go"||a[1].Path!="changed.go"{t.Fatalf("priority=%+v",a)}}
func confirmedChain(idx RepositoryIndex,a,am,b,bm,c,cm string)string{sa:=symbolByOwnerName(idx.Symbols,a,am);sb:=symbolByOwnerName(idx.Symbols,b,bm);sc:=symbolByOwnerName(idx.Symbols,c,cm);if sa.ID==""||sb.ID==""||sc.ID==""{return ""};if hasRelation(idx.Relations,sa.ID,sb.ID,RelationCalls)&&hasRelation(idx.Relations,sb.ID,sc.ID,RelationCalls){return a+"#"+am+" -> "+b+"#"+bm+" -> "+c+"#"+cm};return ""}
func symbolByOwnerName(syms []Symbol,owner,name string)Symbol{for _,s:=range syms{if s.Owner==owner&&s.Name==name{return s}};return Symbol{}}
func hasRelation(rs []Relation,from,to string,k RelationKind)bool{for _,r:=range rs{if r.From==from&&r.To==to&&r.Kind==k{return true}};return false}
func TestChangedFilesRealGitModifiedUntrackedDeleted(t *testing.T){if _,err:=exec.LookPath("git");err!=nil{t.Skip("git unavailable")};root:=t.TempDir();runGit(t,root,"init");runGit(t,root,"config","user.email","test@example.com");runGit(t,root,"config","user.name","Task28");writeRepoFile(t,root,"modified.txt","one");writeRepoFile(t,root,"deleted.txt","bye");runGit(t,root,"add",".");runGit(t,root,"commit","-m","base");writeRepoFile(t,root,"modified.txt","two");if err:=os.Remove(filepath.Join(root,"deleted.txt"));err!=nil{t.Fatal(err)};writeRepoFile(t,root,"new file 中文.txt","new");got:=GitChangedFiles(context.Background(),root,nil);want:=[]string{"deleted.txt","modified.txt","new file 中文.txt"};if !reflect.DeepEqual(got,want){t.Fatalf("changed=%v want=%v",got,want)}}
func runGit(t *testing.T,root string,args ...string){t.Helper();cmd:=exec.Command("git",append([]string{"-C",root},args...)...);if out,err:=cmd.CombinedOutput();err!=nil{t.Fatalf("git %v: %v %s",args,err,out)}}
type recordingRunner struct{name string;args []string;out []byte;err error}
func(r *recordingRunner)Run(_ context.Context,name string,args ...string)([]byte,error){r.name=name;r.args=append([]string(nil),args...);return r.out,r.err}
func TestChangedFilesUsesFixedGitArgvAndFailureIsEmptySignal(t *testing.T){r:=&recordingRunner{out:[]byte(" M a\\b.go\x00?? new.txt\x00")};got:=GitChangedFiles(context.Background(),"C:/repo",r);if r.name!="git"||!reflect.DeepEqual(r.args,[]string{"-C","C:/repo","status","--porcelain=v1","-z","--untracked-files=all"}){t.Fatalf("argv %s %v",r.name,r.args)};if !reflect.DeepEqual(got,[]string{"a/b.go","new.txt"}){t.Fatalf("got=%v",got)};r.err=context.DeadlineExceeded;if got:=GitChangedFiles(context.Background(),"C:/repo",r);len(got)!=0{t.Fatalf("failure signal=%v",got)}}
